signUppObjects/Lyonline/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve


from Lyonline.settings import MEDIA_ROOT
import xadmin
urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^users/',include('users.urls',namespace='user')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^$',TemplateView.as_view(template_name='index.html'),name='index'),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$',serve,{'document_root':STATIC_ROOT}),
    url(r'^course/',include('course.urls',namespace='course')),
    url(r'^pay/',include('tradApp.urls',namespace='alipay')),
    url(r'^operation/',include('operation.urls',namespace='operation')),

]

handler404 = 'users.views.page_not_found'

signUppObjects/course/urls.py
from django.conf.urls import url

from .views import Courselistview,CourseDetailView,CourseInfoView,ActiveDetail,GetCoupon

urlpatterns = [

    # url(r'course_list/(?P<sort>\d+)$',Courselistview.as_view() ,name='courseList'),
    url(r'course_list/$',Courselistview.as_view() ,name='courseList'),
    url(r'course_detail/(?P<course_id>\d+)$',CourseDetailView.as_view() ,name='course_detail'),
    url(r'course_info/(?P<course_id>\d+)$', CourseInfoView.as_view(), name='course_info'),
    url(r'active_detail/(?P<active_id>\d+)$',ActiveDetail.as_view(),name='active_detail'),
    url(r'get_coupon/$',GetCoupon.as_view(),name='get_coupon'),

]

signUppObjects/users/urls.py
from django.conf.urls import url

from .views import LoginView,LogoutView,RegistView,GetveryCode,ForgetView,UserInfoView,UserUploadImageView,UserUploadPwd,UserCouponView,UserOderView

urlpatterns = [

    url(r'login/$',LoginView.as_view(),name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'register/$',RegistView.as_view(),name='register'),
    url(r'getCode/$',GetveryCode.as_view(),name='getcode'),
    # url(r'active/(?P<active_code>.*)/$',ActiveEmail.as_view(),name='active'),
    url(r'forgetpwd/$',ForgetView.as_view(),name='forgetpwd'),
    # url(r'changepwd/(?P<change_code>.*)$',ChangepwdEmail.as_view(),name='change_pwd'),
    # url(r'changeagin/',AginChange.as_view(),name='change_agin'),

    url(r'user_info/',UserInfoView.as_view(),name='user_info'),
    url(r'user_coupon/',UserCouponView.as_view(),name='user_coupon'),
    url(r'user_order/',UserOderView.as_view(),name='user_order'),
    url(r'user_upload_image/',UserUploadImageView.as_view(),name='upload_image'),
    url(r'update/pwd/',UserUploadPwd.as_view(),name='upload_pwd'),

]

signUppObjects/course/models.py
from django.db import models
from datetime import datetime

# from Lyonline.organization.models import CourseOrg
# Create your models here.

#训练场地
class Practiceplace(models.Model):
    title = models.CharField(default='训练场地1',max_length=20,verbose_name='场地名称')
    #后期经纬度
    #long_td = models.DecimalField(max_digits=10, decimal_places=7,verbose_name='经度')#精度
    #lati_td = models.DecimalField(max_digits=10,decimal_places=7,verbose_name='纬度')#纬度
    image = models.ImageField(upload_to='practicplace/%Y/%m',verbose_name=u'封面图')
    detail = models.TextField(verbose_name=u'Tuobaba承诺')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')
    class Meta:
        verbose_name = u'训练场地'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.title

#课程
class Course(models.Model):
    name = models.CharField(max_length=50,verbose_name=u'课程名称')
    detail1 = models.TextField(default='',verbose_name=u'费用详情')
    detail2 = models.TextField(default='',verbose_name=u'赠送课时')
    cost_new = models.CharField(null=True,blank=True,default='4850',max_length=20,verbose_name=u'现价')
    cost_old = models.CharField(null=True,blank=True,default='5000',max_length=20,verbose_name=u'原价')
    image = models.ImageField(upload_to='course/%Y/%m',max_length=200,verbose_name=u'封面图')
    # click_nums = models.IntegerField(default=0,verbose_name=u'点击数')
    practiceplace = models.ForeignKey(Practiceplace,null=True,blank=True,verbose_name=u'练习场地')
    pay_mount = models.CharField(max_length=20,null=True,blank=True,verbose_name=u'支付金额')
    discount = models.CharField(max_length=20,null=True,blank=True,verbose_name=u'优惠金额')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name
    def get_advantages(self):
        return self.advantage_set.all()
    def get_costs(self):
        return self.cost_set.all()

    def __str__(self):
        return self.name

#优势
class Advantage(models.Model):
    course = models.ForeignKey(Course,verbose_name=u'课程')
    detail = models.CharField(max_length=100,verbose_name=u'描述')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')
    class Meta:
        verbose_name = u'课程优势'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.detail

#费用
class Cost(models.Model):
    course = models.ForeignKey(Course,verbose_name=u'相关课程')
    name = models.CharField(max_length=20,verbose_name=u'费用名称')
    money = models.CharField(max_length=10,verbose_name=u'金额')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')
    class Meta:
        verbose_name = u'费用明细'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name

#活动
class Active(models.Model):
    title = models.CharField(default='新春活动',max_length=20,verbose_name='活动名称')
    code = models.IntegerField(default=1,verbose_name='活动编号')
    detail = models.TextField(verbose_name='活动规则')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'活动'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    # def get_coupons(self):
    #     return self.coupon_set.all()

signUppObjects/course/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.views.generic import View
from operation.models import UserCourse
from django.db.models import Q
from .models import Course,Cost,Practiceplace
from tradApp.models import Coupon
from users.models import Banner
from operation.models import UserCoupon

# from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
class Courselistview(View):
    def get(self,request):
        try:
            course1 = Course.objects.get(id=1)
            course2 = Course.objects.get(id=2)
        except:
            print('【+课程列表页】：没有取到课程列表')
        try:
            banners = Banner.objects.all()
        except:
            print('【+课程列表页】：没有取到轮播图')
        return render(request,'enrol.html',{'course1':course1,'course2':course2,'banners':banners})

class CourseDetailView(View):
    def get(self,request,course_id):

        try:
            course = Course.objects.get(id=course_id)
        except:
            print('【+】：没有取到相应课程')

        return render(request,'curriculumDetail.html',{'course':course,})


class CourseInfoView(View):
    def get(self,request,course_id):
        user = request.user
        course = Course.objects.get(id=course_id)
        user_coupons = UserCoupon.objects.filter(user=user)
        if course.name == 'C1超越期望优质课':
            style = '限C1报名'
        else:
            style = '限C2报名'
        coupons = []
        for user_coupon in user_coupons:
            if user_coupon.coupon.belong_course == style:
                if user_coupon.coupon.status == 'onused':
                    coupons.append(user_coupon.coupon)
        mount = 0
        for coupon in coupons:
            mount = mount + int(coupon.coupon_mount)

        course.discount = str(mount)
        course.pay_mount = int(course.cost_new) - mount
        course.save()

        return render(request,'writeOrderForm.html',{'course':course,'coupons':coupons})

from .models import Active
import json
class ActiveDetail(View):
    def get(self,request,active_id):
        if not request.user.is_authenticated:
            #每登录正常显示
            active = Active.objects.get(code=active_id)
            coupons = Coupon.objects.filter(active=active)
            banners = Banner.objects.all()
            return render(request,'getCoupon.html',{'coupons':coupons,'active':active,'banners':banners})
        else:
            #判断 是否领取了  （coupon  是否在 UserCoupon）
            user = request.user
            print('--username-->',user.username)
            try:
                usercoupons = UserCoupon.objects.filter(user=user)

            except:
                active = Active.objects.get(code=active_id)
                coupons = Coupon.objects.filter(active=active)
                banners = Banner.objects.all()
                return render(request, 'getCoupon.html', {'coupons': coupons, 'active': active, 'banners': banners})
            l = []
            for usercoupon in usercoupons:
                l.append(usercoupon.coupon)
            active = Active.objects.get(code=active_id)
            coupons = Coupon.objects.filter(active=active)
            banners = Banner.objects.all()
            return render(request,'getCoupon.html',{'coupons':coupons,'active':active,'banners':banners,'usercoupons':l})
                      
class GetCoupon(View):
    def get(self,request):
        pass
    def post(self,request):
        print('--->???')
        #判断登录状态
        if request.user.is_authenticated():

            coupon_id = request.POST.get('coupon_id','')
            active_id = request.POST.get('active_id','')
            print('-cp-->',coupon_id)
            print('--ac--->', active_id)
            usercoupon = UserCoupon()
            coupon = Coupon.objects.get(code=coupon_id)
            usercoupon.user = request.user
            usercoupon.coupon = coupon
            usercoupon.save()
            print('--->1')
            resp = {'status':200,'msg':'领取成功'}   #前段拿到200 window reload
            return HttpResponse(json.dumps(resp), content_type='application/json')
        else:
            print('--->2')
            # return HttpResponseRedirect('/users/login/')
            resp = {'status':202,'msg':'未登录'}
            return HttpResponse(json.dumps(resp), content_type='application/json')

signUppObjects/templates/course/123.html
{% extends 'course-base.html' %}
{% load staticfiles %}
{% block title %} 课程支付-拓叭吧学车 {% endblock %}
{% block breade %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="index.html">首页</a>></li>
                <li><a href="course-list.html">公开课程</a>></li>
				<li>课程支付</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

signUppObjects/templates/course/course-comment.html
{% extends 'course-base.html' %}
{% load staticfiles %}
{% block title %} 公开课列表-l乐创教育 {% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}
{% block breade %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'course:courseList' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>课程评论</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}
{% block content %}
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">django与vuejs实战项目2</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>高级</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">0分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>12</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="course-video.html"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="course-comment.html"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                            {% for comment in course.get_comment %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.user.image }}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ comment.user.username }}</span>
                                    </div>
                                    <p class="cnt">{{ comment.comments }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">{{ comment.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}


                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">

                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;前端页面</span>
                                <a href="../media/course/resource/2016/11/media.zip" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>

                        </ul>
                    </div>
                        <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='../media/teacher/2016/11/aobama_CXWwMef.png' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">bobby</a>
        </span>
                            <span class="job">xxx</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">python基础你需要有</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">django的进阶开发</dd>
                            </dl>
                        </div>
                    </div>


                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/view/85?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/57035ff200014b8a06000338-240-135.jpg" alt="Java入门第一季">
                                                <span class="name autowrap">Java入门第一季</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/110?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/5703604a0001694406000338-240-135.jpg" alt="Java入门第三季">
                                                <span class="name autowrap">Java入门第三季</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/124?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/570360620001390f06000338-240-135.jpg" alt="Java入门第二季">
                                                <span class="name autowrap">Java入门第二季</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/47?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/570765d90001bf1406000338-240-135.jpg" alt="Spring MVC起步">
                                                <span class="name autowrap">Spring MVC起步</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/view/36?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/53e1d0470001ad1e06000338-240-135.jpg" alt="JavaScript入门篇">
                                                <span class="name autowrap">JavaScript入门篇</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                                <span class="name autowrap">Java工程师</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>

{% endblock %}

{% block custom_js %}
<script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val()
        if(comments == ""){
            alert("评论不能为空")
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'course:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="login.html";
                    }else{
                        alert(data.msg)
                    }

                }else if(data.status == 'success'){
                    window.location.reload();//刷新当前页面.
                }
            },
        });
    });

</script>
{% endblock %}

signUppObjects/templates/course/course-list.html
{% extends 'course-base.html' %}
{% load staticfiles %}
{% block title %} 公开课列表-l乐创教育 {% endblock %}
{% block breade %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="{% if sort == '' %}active{% else %}{% endif %}"><a href="?sort=">最新 </a></li>
						<li class="{% if sort == 'hot' %}active{% else %}{% endif %}"><a href="?sort=hot">最热门</a></li>
						<li class="{% if sort == 'students' %}active{% else %}{% endif %}"><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                            {% for course in courses_list.object_list %}
                            <div class="box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="course-detail.html"><span class="fl">拓叭叭学车网</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        1
                                    </span>
                                </div>
                            </div>
                            {% endfor %}




					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
                        {% if courses_list.has_previous %}
                            <li class="long" ><a href="?{{ courses_list.previous_page_number.querystring }}" >上一页</a></li>
                        {% else %}

                        {% endif %}
                        {% for page in courses_list.pages %}
                            {% if page %}
                                {% ifequal page courses.number %}
                                <li class="active"><a>{{ page }}</a></li>
                                {% else %}
                                <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                {% endifequal %}
                            {% else %}

                            {% endif %}

                        {% endfor %}
                        {% if courses_list.has_next %}
                            <li class="long"> <a href="?{{ courses_list.next_page_number.querystring }}" >下一页</a></li>
                        {% else %}

                        {% endif %}

                        </ul>

                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">

                    <dl>
						<dt>
							<a target="_blank" href="">
								<img width="240" height="220" class="scrollLoading" src="{% static 'media/courses/2016/11/540e57300001d6d906000338-240-135_n0L8vbw.jpg' %}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2> django与vuejs实战项目2</h2></a>
							<span class="fl">难度：<i class="key">高级</i></span>
						</dd>
					</dl>

                    <dl>
						<dt>
							<a target="_blank" href="">
								<img width="240" height="220" class="scrollLoading" src="{% static 'media/courses/2016/12/python面向对象.jpg' %}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2> python面向对象</h2></a>
							<span class="fl">难度：<i class="key">中级</i></span>
						</dd>
					</dl>

                    <dl>
						<dt>
							<a target="_blank" href="">
								<img width="240" height="220" class="scrollLoading" src="{% static 'media/courses/2016/12/python文件处理.jpg"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2> python文件处理</h2></a>
							<span class="fl">难度：<i class="key">中级</i></span>
						</dd>
					</dl>



				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

signUppObjects/templates/course/course-video.html
{% extends 'course-base.html' %}
{% load staticfiles %}
{% block title %} {% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
	<!--<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">-->
	<!--<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">-->
	<!--<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">-->

{% endblock %}
{% block breade %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'course:courseList' %}">驾驶课程</a>></li>
				<li><a href="{% url 'course:course_detail' course.id %}">支付界面</a>></li>
                <li>订单详情</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}
{% block content %}
    <div id="main">

    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:course_info'  course.id  %}"><span>订单</span></a></li>
                        <li><a id="commentOn" class="" href=" {% url 'course:course_comment'  course.id  %}"><span></span></a></li>
                    </ul>
                </div>

                <form id="email_register_form" method="get" action="" autocomplete="off">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon0">课程名</span>
                        <input value="{{ coach_order.course_name }}" type="text"  name="order_sn" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon">教练</span>
                        <input value="汪鹏" type="text" name="username" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">金额</span>
                        <input value="4680" type="text" name="order_mount" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon2">用户名</span>
                        <input value="徐璟灏" type="text" name="coach_name" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon3">支付方式</span>
                        <a href="?style=aplipay&order_sn={{ coach_order.order_sn }}"><span class="{% ifequal style 'aplipay' %} active2 {% endifequal %}">支付宝支付</span></a>
                        <a href="?style=wechat&order_sn={{ coach_order.order_sn }}"><span class="{% ifequal style 'wechat' %} active2 {% endifequal %}">微信支付</span></a>

                        <!--<input value="aplipay" type="text" name="pay_type" class="form-control" placeholder="Username" aria-describedby="basic-addon1">-->
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon4">实付金额</span>
                        <input value="4580" type="text" name="pay_mount" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
                    </div>
                    <a class="btn btn-default" href="{{ alipay_url }}" role="button">提交订单</a>
                        {% csrf_token %}
                </form>

            </div>

        </div>
        <div class="clear"></div>

    </div>

</div>
</div>

{% endblock %}



