signUppObjects/Lyonline/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve


from Lyonline.settings import MEDIA_ROOT
import xadmin
urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^users/',include('users.urls',namespace='user')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^$',TemplateView.as_view(template_name='index.html'),name='index'),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$',serve,{'document_root':STATIC_ROOT}),
    url(r'^course/',include('course.urls',namespace='course')),
    url(r'^pay/',include('tradApp.urls',namespace='alipay')),
    url(r'^operation/',include('operation.urls',namespace='operation')),

]

handler404 = 'users.views.page_not_found'

signUppObjects/users/urls.py
from django.conf.urls import url

from .views import LoginView,LogoutView,RegistView,GetveryCode,ForgetView,UserInfoView,UserUploadImageView,UserUploadPwd,UserCouponView,UserOderView

urlpatterns = [

    url(r'login/$',LoginView.as_view(),name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'register/$',RegistView.as_view(),name='register'),
    url(r'getCode/$',GetveryCode.as_view(),name='getcode'),
    # url(r'active/(?P<active_code>.*)/$',ActiveEmail.as_view(),name='active'),
    url(r'forgetpwd/$',ForgetView.as_view(),name='forgetpwd'),
    # url(r'changepwd/(?P<change_code>.*)$',ChangepwdEmail.as_view(),name='change_pwd'),
    # url(r'changeagin/',AginChange.as_view(),name='change_agin'),

    url(r'user_info/',UserInfoView.as_view(),name='user_info'),
    url(r'user_coupon/',UserCouponView.as_view(),name='user_coupon'),
    url(r'user_order/',UserOderView.as_view(),name='user_order'),
    url(r'user_upload_image/',UserUploadImageView.as_view(),name='upload_image'),
    url(r'update/pwd/',UserUploadPwd.as_view(),name='upload_pwd'),

]

signUppObjects/users/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class UserProfile(AbstractUser):
    #默认有username 字段
    nick_name = models.CharField(null=True,blank=True, max_length=50, verbose_name=u'昵称',default=u'拓吧叭学员')
    true_name = models.CharField(null=True,blank=True,max_length=50,verbose_name=u'真实姓名')
    sex = models.CharField(max_length=5,choices=(('male',u'男'),('female',u'女')))
    telphone = models.CharField(max_length=11,null=True,blank=True)
    image = models.ImageField(upload_to='image/%Y/%m',default=u'image/aobama.png',max_length=100)

    class Meta:
        verbose_name = u'用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class TelNumVerifyRecord(models.Model):

    code = models.CharField(max_length=20,verbose_name=u'验证码')
    telnum = models.CharField(max_length=50,verbose_name=u'电话号码')
    send_type = models.CharField(max_length=20,choices=(('register',u'注册'),('forget',u'忘记密码')))
    send_time = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = u'短信验证'
        verbose_name_plural = verbose_name

    def  __str__(self):
        return '{0}({1})'.format(self.code,self.telnum)

class Banner(models.Model):
    title = models.CharField(max_length=100,verbose_name=u'标题')
    image = models.ImageField(max_length=200,upload_to='banner/%y/%m',verbose_name=u'轮播')
    url = models.URLField(default='http://192.168.192.136:8000/course/get_coupon/1',max_length=200,verbose_name=u'访问地址')
    detail = models.CharField(max_length=20,default='新春活动1',verbose_name=u'活动描述')
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u'添加日期')

    class Meta:
        verbose_name = u'轮播图'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

signUppObjects/users/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile
class LoginForm(forms.Form):
    username = forms.RegexField(regex='^1[356789]\d{9}$',error_messages={'required':u'手机号不能为空','invalid':u'手机号格式不正确'})
    password = forms.CharField(min_length=6,error_messages={'required':u'密码不能为空','invalid':u'密码设置过短'})
    captcha = CaptchaField(error_messages={'required':u'验证码不能为空','invalid': u'验证码出错'})

class RegisterForm(forms.Form):
    username = forms.RegexField(regex='^1[356789]\d{9}$',error_messages={'required':u'手机号不能为空','invalid':u'手机号格式不正确'})
    password1 = forms.CharField(min_length=6, error_messages={'required': u'密码不能为空', 'invalid': u'密码设置过短'})
    password2 = forms.CharField(min_length=6, error_messages={'required': u'密码不能为空', 'invalid': u'密码设置过短'})
    verifyNum = forms.CharField(error_messages = {'invalid':u'验证码出错'})

class ForgetForm(forms.Form):
    username = forms.RegexField(regex='^1[356789]\d{9}$',error_messages={'required':u'手机号不能为空','invalid':u'手机号格式不正确'})
    password1 = forms.CharField(min_length=6, error_messages={'required': u'密码不能为空', 'invalid': u'密码设置过短'})
    password2 = forms.CharField(min_length=6, error_messages={'required': u'密码不能为空', 'invalid': u'密码设置过短'})
    verifyNum = forms.CharField(error_messages = {'invalid':u'验证码出错'})

class ChangeForm(forms.Form):
    password = forms.CharField(required=True,min_length=6)
    password2 = forms.CharField(required=True,min_length=6)

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']

signUppObjects/users/views.py
from django.contrib.auth import authenticate, login, hashers,logout
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.contrib.auth.hashers import make_password,check_password
import json,random
from datetime import datetime,timedelta
# from  utils.util import send_email
from .forms import LoginForm,RegisterForm,ForgetForm,ChangeForm,UploadImageForm
from .models import UserProfile,TelNumVerifyRecord

# Create your views here.

class CustomBackend(ModelBackend):
    def authenticate(self, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username)|Q(email=username)|Q(nick_name=username))
            if user.check_password(password):
                return user
            return None

        except Exception as e :
            print(e)
            return None

#忘记密码
class ForgetView(View):
    def get(self,request):
        forget_form = ForgetForm()
        return render(request, 'forgetpwd.html', {'forget_form':forget_form})
    def post(self,request):
        forget_form = ForgetForm(request.POST)
        if forget_form.is_valid():
            passw1 = request.POST.get('password1', '')
            passw2 = request.POST.get('password2', '')
            if passw1 != passw2:
                return render(request, 'forgetpwd.html', {'forget_form': forget_form, 'msg': '两次输入密码不一致'})
            telphone = request.POST.get('username', '')
            code = request.POST.get('verifyNum', '')
            send_type = request.POST.get('send_type','')
            try:
                user = UserProfile.objects.get(telphone=telphone)
            except:
                return render(request, 'forgetpwd.html', {'forget_form': forget_form, 'msg': '该手机号未注册'})
            try:
                VerifyRecord = TelNumVerifyRecord.objects.filter(telnum=telphone, code=code,send_type=send_type).order_by('-add_time')[0]
                five_munite_ago = datetime.now() - timedelta(hours=0,minutes=5,seconds=0)
                if VerifyRecord:
                    if VerifyRecord.add_time  < five_munite_ago:
                        return render(request, 'forgetpwd.html', {'forget_form': forget_form, 'msg': '验证码已过期'})
                    elif VerifyRecord.code != code:
                        return render(request, 'forgetpwd.html', {'forget_form': forget_form, 'msg': '验证码不符请重试'})
                    try:
                        pwd = hashers.make_password(passw1)
                        user.password = pwd
                        user.save()
                    except:
                        print('【+】：将数据保存后台出错')
                        return render(request, 'forgetpwd.html', {'forget_form': forget_form, 'msg': '网络延迟'})
                    return HttpResponseRedirect('/users/login/')
            except:
                return render(request, 'forgetpwd.html', {'forget_form': forget_form, 'msg': '内部服务器错误，请重试'})
        else:
            return render(request, 'forgetpwd.html', {'forget_form': forget_form})


class LoginView(View):
    def get(self,request):
        login_form = LoginForm()
        j = request.GET.get('j', '')
        course_id = request.GET.get('course_id', '')
        return render(request, 'login.html', {'login_form': login_form, 'j': j, 'course_id': course_id})

    def post(self,request):
        login_form = LoginForm(request.POST)
        j = request.POST.get('j', '')
        course_id = request.POST.get('course_id', '')

        if login_form.is_valid():
            username = request.POST.get('username','')
            password1 = request.POST.get('password','')

            try:
                user = UserProfile.objects.get(username=username)
            except:
                return render(request, 'login.html', {'login_form':login_form, 'msg': '该手机号未注册', 'j':j, 'course_id':course_id})
            user = authenticate(username = username,password = password1)
            if user is  None:
                return render(request, 'login.html', {'login_form':login_form, 'msg': '用户名或密码错误', 'j':j, 'course_id':course_id})
            else:
                login(request, user)

                print('--->oldme-->',j)
                if j == '2':
                    return HttpResponseRedirect('/course/course_info/{0}'.format(course_id))
                elif j == '1':
                    return HttpResponseRedirect('/users/user_info')
                elif j == '3':
                    return HttpResponseRedirect('/course/active_detail/1')
                return HttpResponseRedirect('/')
        return render(request, 'login.html', {'login_form':login_form, 'j':j, 'course_id':course_id})


from utils.send_code import YunPian
from datetime import datetime,timedelta
from django.views.decorators.csrf import csrf_exempt,csrf_protect

class GetveryCode(View):
    def get(self,request):
        pass
    @csrf_exempt
    def post(self,request):
        telnum = request.POST.get('phone', '')
        VerifyRecord = TelNumVerifyRecord.objects.filter().order_by('-add_time')[0]
        four_munite_ago = datetime.now() - timedelta(hours=0,minutes=4,seconds=0)
        if VerifyRecord:
            if VerifyRecord.add_time > four_munite_ago:
                resp = {'status': 404, 'code': VerifyRecord.code, 'msg': '请求频繁'}
                return HttpResponse(json.dumps(resp), content_type='application/json')

        print('---号码发送验证码---->',telnum)
        send_type = request.POST.get('send_type','')
        if telnum == '':
            print('【获取验证码】电话号码为空')
        yun_pain = YunPian('05e6858c497059ebea9bc5b81b08f37d')
        code = yun_pain.get_code()
        status = yun_pain.send_code(code,telnum,send_type)
    #2分钟让它失效
        if status == '发送成功':
            resp = {'status': 200, 'code':code,'msg':'发送成功' }
            #将验证码保存到表中
            VerifyRecord = TelNumVerifyRecord()
            VerifyRecord.code = code
            VerifyRecord.telnum = telnum
            VerifyRecord.send_type = send_type
            VerifyRecord.save()
        else:
            resp = {'status':404,'code':code,'msg':'请求频繁'}
        return HttpResponse(json.dumps(resp), content_type='application/json')

class RegistView(View):
    def get(self,request):
        register_form = RegisterForm()
        return render(request, 'register.html', {'register_form':register_form})
    def post(self,request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            passw1 = request.POST.get('password1','')
            passw2 = request.POST.get('password2','')
            if passw1 != passw2:
                return render(request, 'register.html', {'register_form':register_form, 'msg': '两次输入密码不一致'})
            telphone = request.POST.get('username','')
            code = request.POST.get('verifyNum','')
            try:
                user = UserProfile.objects.get(telphone=telphone)
                if user:
                    return render(request, 'register.html', {'register_form':register_form, 'msg': '该手机号已注册过'})
            except:
                print('【+】该手机可以注册')
            try:
                VerifyRecord = TelNumVerifyRecord.objects.filter(telnum=telphone,code=code,send_type='register').order_by('-add_time')[0]
                if VerifyRecord:
                    five_minute_ago = datetime.now() - timedelta(hours=0,minutes=5,seconds=0)
                    if VerifyRecord.add_time < five_minute_ago:
                        return render(request, 'register.html', {'register_form': register_form, 'msg': '验证码已经过期'})
                    else:
                        password = request.POST.get('password1', '')
                        username = request.POST.get('username', '')
                        try:
                            user = UserProfile()
                            user.username = username
                            user.telphone = telphone
                            user.set_password(password)
                            user.save()
                        except:
                            print('【+】：将数据保存后台出错')
                            return render(request, 'register.html', {'register_form': register_form, 'msg': '网络延迟'})
                        return HttpResponseRedirect('/users/login/')  # http://www.baidu.com/‘
            except:
                return render(request, 'register.html', {'register_form':register_form, 'msg': '服务器内部出错,请重试'})
        else:
            return render(request, 'register.html', {'register_form':register_form})
#------------------个人详情页---------------------------------------------------------------------------------------------->>>>
from django.contrib import auth

class LogoutView(View):
    def get(self,request):
        logout(request)
        return HttpResponseRedirect('/login')

class UserInfoView(View):
    def get(self,request):
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/users/login?j=1')
        return render(request,'personalInfo.html')


class UserCouponView(View):
    def get(self,request):
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/users/login?j=1')
        user = request.user
        style = request.GET.get('style','onuse')
        if style == 'onuse':
            should_use = []
            #未使用
            coupons = UserCouponView.objects.filter(user=user,status='onused')
        elif style == 'used':
            #已经使用
            coupons = UserCouponView.objects.filter(user=user, status='used')
        elif style == 'tolate':
            #过期
            coupons = UserCouponView.objects.filter(user=user, status='used')
        return render(request,'personalCoupon.html',{'coupons':coupons,'style':style})


class UserOderView(View):
    def get(self, request):

signUppObjects/templates/user/forgetpwd.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="author" content="tuobaba"/>
    <title>杭州拓叭吧科技有限公司</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/tbb.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/font/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/focusStyle.css' %}">
    <!--<link rel="shortcut icon" href="4-1.ico" type="image/x-icon" />-->

</head>
<body>
<div class="nav" style="margin-bottom: 604px">
    <div class="nav-s container">
        <div class="nav-log"></div>
        <div class="nav-nav">
            <ul class="nav-ul">
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="../utils/index.html?showGet=0" class="tbb-a1">首页</a>
                    </div>
                    <div class="nav-down show-4"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="enrol.html?showGet=1" class="tbb-a1">我要报名</a>
                    </div>
                    <div class="nav-down show-3"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="../utils/kitcar.html?showGet=2" class="tbb-a1">KITCAR</a>
                    </div>
                    <div class="nav-down show-3"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="../utils/app.html?showGet=3" class="tbb-a1">下载APP</a>
                    </div>
                    <div class="nav-down show-2"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="../utils/about.html?showGet=4" class="tbb-a1">关于我们</a>
                    </div>
                    <div class="nav-down show-1"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="join.html?showGet=5" class="tbb-a1">加入我们</a>
                    </div>
                    <div class="nav-down show-0"></div>
                </li>
                <li class="nav-li1"><i class="fa fa-car"></i></li>
            </ul>
            <div class="login"><a href="login.html">登录</a></div>
            <div class="register"><a href="register.html">注册</a></div>
        </div>
        <div class=" switchMenuBtn"><span class="one"></span><span class="two"></span><span class="three"></span></div>
    </div>
</div>
<div class="registerDiv">
    <div class=" loginBg thumbnail">
        <img src="{% static 'images/loginPageBg.png' %}" alt="Image"/>
        <div class="container">
            <div class="register-table col-xs-12  col-sm-8 col-md-6 col-lg-6">
                <div>
                    <h2>忘记密码</h2>
                    <form action="{% url 'user:forgetpwd' %}" method="post" autocomplete="off">

                    <div class="phone">
                        <input id="phone" type="text" name="username" value="{{ forget_form.username.value|default_if_none:'' }}" placeholder="输入你的手机号">
                    </div>
                    <div class="password">
                        <input id="password" type="password" name="password1" value="{{ forget_form.password1.value|default_if_none:'' }}" placeholder="输入密码(密码长度6-12)">
                    </div>
                    <div class="password">
                        <input id="checkPassword" type="password" name="password2" value="{{ forget_form.password2.value|default_if_none:'' }}" placeholder="请确认密码(密码长度6-12)">
                    </div>
                        <input type="hidden" id="send_type" name='send_type' value="forget">
                    <div class="verifyNum">
                        <input id="verifyNum" type="text" name="verifyNum" value="{{ forget_form.verifyNum.value|default_if_none:'' }}" placeholder="输入4位手机验证码">
                        <div class="getPhoneVerifyNum"><span>点击获取验证码</span></div>
                        <div class="clear"></div>
                    </div>
                    {% for keys,error in register_form.errors.items %}
                    <div class="errorInf">
                        <span>{{ error }}</span>
                    </div>
                    {% endfor %}
                    <div class="errorInf"><span>{{ msg }}</span></div>
                    <div class="toRegist"><span>已有账号?</span> <a href="{% url 'user:login' %}">去登录</a></div>
                    <button class="submit">修改密码</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="footer">
    <!--<div class="f-title"><span>Tuobaba</span>学车</div>-->
    <div class="ff-logo"></div>
    <div class="f-tit">一开始就玩真的</div>
    <div class="f-tit-say" style="line-height: 40px">
        <span>客服：400-8875828</span>
        <span>杭州拓叭吧科技有限公司</span>
    </div>
    <div class="f-tit-say">杭州市滨江区六合路368号一幢（北）二楼B2112室</div>
    <div class="f-tit-say">
        <a class="tbb-a2" href="javascript:;" style=" position: relative">
            <i class="fa fa-weixin"></i>
            <div id="show-erweima"></div>
        </a>
        <a class="tbb-a2" href="http://weibo.com/u/6315803035"><i class="fa fa-weibo"></i></a>
    </div>
    <div class="l-tit">Copyright © 2017 TuoBaBa Inc. 保留所有权利。 | Hangzhou TuoBaBa Technology Co., Ltd. 商务合作邮箱
        tbb@tuobbkj.com
    </div>
</div>

<script src="{% static 'js/jquery-1.11.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/tbb.js' %}" type="text/javascript"></script>
<!--[if lt IE 9]>
<script src="{% static 'js/html5shiv.js' %}"></script>
<script src="{% static 'js/respond.min.js' %}"></script>
<![endif]-->
<script src="{% static 'js/utile.js' %}"></script>
<script src="{% static 'js/loading.js' %}"></script>
<script src="{% static 'js/login.js' %}"></script>
 <script src="{% static 'js/config.js' %}" type="text/javascript"></script>
<script>


</script>
</body>

</html>

signUppObjects/templates/user/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="author" content="tuobaba"/>
    <title>杭州拓叭吧科技有限公司</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/tbb.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/font/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/focusStyle.css' %}">
    <!--<link rel="shortcut icon" href="4-1.ico" type="image/x-icon" />-->

</head>
<body>
<div class="nav" style="margin-bottom: 604px">
    <div class="nav-s container">
        <div class="nav-log"></div>
        <div class="nav-nav">
            <ul class="nav-ul">
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="../utils/index.html?showGet=0" class="tbb-a1">首页</a>
                    </div>
                    <div class="nav-down show-4"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="enrol.html?showGet=1" class="tbb-a1">我要报名</a>
                    </div>
                    <div class="nav-down show-3"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="../utils/kitcar.html?showGet=2" class="tbb-a1">KITCAR</a>
                    </div>
                    <div class="nav-down show-3"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="../utils/app.html?showGet=3" class="tbb-a1">下载APP</a>
                    </div>
                    <div class="nav-down show-2"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="../utils/about.html?showGet=4" class="tbb-a1">关于我们</a>
                    </div>
                    <div class="nav-down show-1"></div>
                </li>
                <li class="nav-li">
                    <div class="nav-con">
                        <a href="join.html?showGet=5" class="tbb-a1">加入我们</a>
                    </div>
                    <div class="nav-down show-0"></div>
                </li>
                <li class="nav-li1"><i class="fa fa-car"></i></li>
            </ul>
            <div class="login"><a href="login.html">登录</a></div>
            <div class="register"><a href="users/register/">注册</a></div>
        </div>
        <div class=" switchMenuBtn"><span class="one"></span><span class="two"></span><span class="three"></span></div>
    </div>
</div>
<div class="loginDiv">
    <div class=" loginBg thumbnail">
        <img src="{% static 'images/loginPageBg.png' %}" alt="Image"/>
        <div class="container">
            <div class="login-table col-xs-12  col-sm-8 col-md-6 col-lg-6">
                <div>
                    <h2>登录</h2>
                    <form action="{% url 'user:login' %}" method="post" autocomplete="off">
                    <div class="phone">
                        <input id="phone" type="text" name="username" value="{{ login_form.username.value|default_if_none:'' }}" placeholder="输入你的手机号">
                    </div>

                    <div class="password">
                        <input id="password" type="password" name="password" value="{{ login_form.password.value|default_if_none:'' }}" placeholder="输入密码">
                    </div>
                        <input type='hidden'  name='j' value='{{ j }}' />
                        <input type='hidden'  name='course_id' value='{{ course_id }}' />

                    <div class="verifyNum">
                        {{ login_form.captcha }}
                        <div class="changeNum">
                        <a href=" " onClick="window.location.reload( true );">换一张</a>
                    </div>
                        <!--<input id="verifyNum" type="text" na me="verifyNum" placeholder="输入验证码">-->
                        <!--<img src="images/" alt="1528">-->
                        <input type='hidden' id='csrfmiddlewaretoken' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy' />
                        <div class="clear"></div>
                    </div>

                    <div class="errorInf">
                    {% for keys,error in login_form.errors.items %}
                        <span> {{error}} </br></span>
                    {% endfor %}
                    </div>
                    <div class="errorInf">
                        <span> {{ msg }} </span>
                    </div>
                    <div class="toRegist"><a href="{% url 'user:forgetpwd' %}">忘记密码</a> <a href="{% url 'user:register' %}">立即注册</a></div>
                    <input class="submit"  type="submit" value="登录" />
                    <!--<button class="submit">登录</button>-->
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer">
    <!--<div class="f-title"><span>Tuobaba</span>学车</div>-->
    <div class="ff-logo"></div>
    <div class="f-tit">一开始就玩真的</div>
    <div class="f-tit-say" style="line-height: 40px">
        <span>客服：400-8875828</span>
        <span>杭州拓叭吧科技有限公司</span>
    </div>
    <div class="f-tit-say">杭州市滨江区六合路368号一幢（北）二楼B2112室</div>
    <div class="f-tit-say">
        <a class="tbb-a2" href="javascript:;" style=" position: relative">
            <i class="fa fa-weixin"></i>
            <div id="show-erweima"></div>
        </a>
        <a class="tbb-a2" href="http://weibo.com/u/6315803035"><i class="fa fa-weibo"></i></a>
    </div>
    <div class="l-tit">Copyright © 2017 TuoBaBa Inc. 保留所有权利。 | Hangzhou TuoBaBa Technology Co., Ltd. 商务合作邮箱
        tbb@tuobbkj.com
    </div>
</div>
<script src="{% static 'js/jquery-1.11.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/tbb.js' %}" type="text/javascript"></script>
<!--[if lt IE 9]>
<script src="{% static 'js/html5shiv.js' %}"></script>
<script src="{% static 'js/respond.min.js' %}"></script>
<![endif]-->
<script src="{% static 'js/utile.js' %}"></script>
<script src="{% static 'js/loading.js' %}"></script>
<script src="{% static 'js/login.js' %}"></script>
 <script src="{% static 'js/config.js' %}" type="text/javascript"></script>
<script>

</script>
</body>

</html>

signUppObjects/templates/user/personalOrder.html
{% extends 'personal_base.html' %}
{% load staticfiles %}

{% block content %}
           <div class=" personalRight col-md-10 col-lg-10 col-sm-12">

        <div class="displayContent entryOrderContent active " id="entryOrderContent">
            <h4>报名订单</h4>
            <div class="entryOrder">
                <div class="formHead">
                    <span>订单详情</span>
                    <span>支付金额</span>
                    <span>支付时间</span>
                </div>
                <div class="orderNum"><span> 订单号：</span><span>695784512365</span></div>
                <div class="formBody">
                    <span class="curriculumName">C1超越期望优质课</span>
                    <span class="prize">￥4850.00</span>
                    <span class="time">2018-03-28-00:00:00 </span>
                </div>
            </div>
        </div>



        </div>
{% endblock %}